### ISSUE TITLE
HandshakeTimeoutError: Handshake timed out

### ISSUE THREAD

**Issue by AbdallahHemdan** [DataDog/apps#149]
I have followed the same steps mentioned [here in the documentation](https://docs.datadoghq.com/developers/datadog_apps/) for Datadog apps, But I am facing an issue in the `starter-kit` as following

- Run the `starter-kit`
- Click on `Click here to open your widget`
- When I try to click the `HERE` button I get the following error message

```
Uncaught (in promise) HandshakeTimeoutError: Handshake timed out
```
![image](https://user-images.githubusercontent.com/40190772/186642246-8e000846-f675-4532-b309-2f8f130da5ba.png)

- Node version: v14.17.0

**Comment by AbdallahHemdan** [comment]
@rachelnicole It would be great if you could support here

**Comment by rachelnicole** [comment]
@AbdallahHemdan can you provide the entire error with the stack trace / screenshot of the console. Also browser info

**Comment by ericrallen** [comment]
@AbdallahHemdan Hey there!

You'll see this error message while viewing the widget locally because the Datadog Apps SDK cannot connect to the Datadog application.

These Datadog Apps are designed to run in an iframe inside of the Datadog UI ([described in more detail in this architecture document](https://github.com/DataDog/apps/blob/master/docs/en/programming-model.md)).

Did you see this error after following the instructions to create a new Developer Platform App and [adding your app to a Dashboard](https://docs.datadoghq.com/developers/datadog_apps/#add-your-app-to-a-dashboard)?

**Comment by AbdallahHemdan** [comment]
@rachelnicole Thanks, I think @ericrallen commit to update the docs make sense now 🙏🏻
